sudo: required

language: go

go:
  - 1.7

services:
  - docker

cache:
  directories:
    - /home/travis/docker/

before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz


script:
  - mkdir -p workspace/logs
  - go build && go install
  - hive --client=ethereumj:master --docker-noshell --smoke=false --test=.
  - mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE};

